"""mkroom.py — provisioner N frpc proxy cho VHOST_HOST={name} (C12).
Sinh file frpc-room.toml với N proxy http chung 1 localPort, subdomain link-01..link-N.
Guard đặt VHOST_HOST="{name}.tunnel.example.com" sẽ route mỗi room/link về đúng proxy.
Usage:
  python scripts/mkroom.py --server VPS_IP --token XXX --local-port 3000 --count 20 --out frpc-room.toml
Stdlib only.
"""
import argparse

TEMPLATE = """# Auto-generated by scripts/mkroom.py - DO NOT EDIT BY HAND
serverAddr = "{server}"
serverPort = {port}
auth.method = "token"
auth.token = "{token}"
transport.tls.enable = true
transport.tcpMux = true

"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--server", required=True)
    ap.add_argument("--token", required=True)
    ap.add_argument("--port", type=int, default=7000)
    ap.add_argument("--local-port", type=int, required=True)
    ap.add_argument("--count", type=int, default=20)
    ap.add_argument("--prefix", default="link")
    ap.add_argument("--out", default="frpc-room.toml")
    a = ap.parse_args()
    out = [TEMPLATE.format(server=a.server, port=a.port, token=a.token)]
    for i in range(1, a.count + 1):
        name = f"{a.prefix}-{i:02d}"
        out.append(
            f'[[proxies]]\nname = "{name}"\ntype = "http"\n'
            f'localIP = "127.0.0.1"\nlocalPort = {a.local_port}\n'
            f'subdomain = "{name}"\n\n'
        )
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("".join(out))
    print(f"wrote {a.out} with {a.count} proxies (prefix={a.prefix})")


if __name__ == "__main__":
    main()
